class Failures {
  final String message;
  const Failures([this.message = "An unexpected error occur"]);
}
